//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CookBookApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CookBookApp.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string addRecipes_bttnUpload {
            get {
                return ResourceManager.GetString("addRecipes_bttnUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lactose, Peanuts, etc....
        /// </summary>
        public static string addRecipes_ntrAllergens {
            get {
                return ResourceManager.GetString("addRecipes_ntrAllergens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to John Doe.
        /// </summary>
        public static string addRecipes_ntrAuthor {
            get {
                return ResourceManager.GetString("addRecipes_ntrAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4....
        /// </summary>
        public static string addRecipes_ntrPortion {
            get {
                return ResourceManager.GetString("addRecipes_ntrPortion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 hours....
        /// </summary>
        public static string addRecipes_ntrPreparationTime {
            get {
                return ResourceManager.GetString("addRecipes_ntrPreparationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100....
        /// </summary>
        public static string addRecipes_ntrPrice {
            get {
                return ResourceManager.GetString("addRecipes_ntrPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lasagne.
        /// </summary>
        public static string addRecipes_ntrRecipeName {
            get {
                return ResourceManager.GetString("addRecipes_ntrRecipeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string CONS_Back {
            get {
                return ResourceManager.GetString("CONS_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string CONS_bttnUpload {
            get {
                return ResourceManager.GetString("CONS_bttnUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string CONS_Difficulty_Advanced {
            get {
                return ResourceManager.GetString("CONS_Difficulty_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginner.
        /// </summary>
        public static string CONS_Difficulty_Beginner {
            get {
                return ResourceManager.GetString("CONS_Difficulty_Beginner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intermediate.
        /// </summary>
        public static string CONS_Difficulty_Intermediate {
            get {
                return ResourceManager.GetString("CONS_Difficulty_Intermediate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading failed.
        /// </summary>
        public static string CONS_FailedUpload {
            get {
                return ResourceManager.GetString("CONS_FailedUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string CONS_Forward {
            get {
                return ResourceManager.GetString("CONS_Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredients.
        /// </summary>
        public static string CONS_Ingredients {
            get {
                return ResourceManager.GetString("CONS_Ingredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allergens.
        /// </summary>
        public static string CONS_lblAllergens {
            get {
                return ResourceManager.GetString("CONS_lblAllergens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string CONS_lblAuthor {
            get {
                return ResourceManager.GetString("CONS_lblAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string CONS_lblCategories {
            get {
                return ResourceManager.GetString("CONS_lblCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        public static string CONS_lblCreationDate {
            get {
                return ResourceManager.GetString("CONS_lblCreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulty.
        /// </summary>
        public static string CONS_lblDifficulty {
            get {
                return ResourceManager.GetString("CONS_lblDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portions.
        /// </summary>
        public static string CONS_lblPortion {
            get {
                return ResourceManager.GetString("CONS_lblPortion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparation time.
        /// </summary>
        public static string CONS_lblPreparationTime {
            get {
                return ResourceManager.GetString("CONS_lblPreparationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string CONS_lblPrice {
            get {
                return ResourceManager.GetString("CONS_lblPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe Name.
        /// </summary>
        public static string CONS_lblRecipeName {
            get {
                return ResourceManager.GetString("CONS_lblRecipeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparation.
        /// </summary>
        public static string CONS_Preparation {
            get {
                return ResourceManager.GetString("CONS_Preparation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        public static string CONS_Price_Average {
            get {
                return ResourceManager.GetString("CONS_Price_Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheap.
        /// </summary>
        public static string CONS_Price_Cheap {
            get {
                return ResourceManager.GetString("CONS_Price_Cheap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expensive.
        /// </summary>
        public static string CONS_Price_Expensive {
            get {
                return ResourceManager.GetString("CONS_Price_Expensive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry from the start.
        /// </summary>
        public static string CONS_RetryAddRecipe {
            get {
                return ResourceManager.GetString("CONS_RetryAddRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfuly uploaded.
        /// </summary>
        public static string CONS_SuccessfulUpload {
            get {
                return ResourceManager.GetString("CONS_SuccessfulUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload in progress.
        /// </summary>
        public static string CONS_Uploading {
            get {
                return ResourceManager.GetString("CONS_Uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View recipe.
        /// </summary>
        public static string CONS_ViewRecipe {
            get {
                return ResourceManager.GetString("CONS_ViewRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Recipe.
        /// </summary>
        public static string menu_bttnAddRecipes {
            get {
                return ResourceManager.GetString("menu_bttnAddRecipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipes.
        /// </summary>
        public static string menu_bttnRecipes {
            get {
                return ResourceManager.GetString("menu_bttnRecipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string menu_bttnSettings {
            get {
                return ResourceManager.GetString("menu_bttnSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main page.
        /// </summary>
        public static string menu_lblMenu {
            get {
                return ResourceManager.GetString("menu_lblMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string recipes_bttnFilter {
            get {
                return ResourceManager.GetString("recipes_bttnFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.....
        /// </summary>
        public static string recipes_srchBrRecipes {
            get {
                return ResourceManager.GetString("recipes_srchBrRecipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Language.
        /// </summary>
        public static string setting_bttnLanguage {
            get {
                return ResourceManager.GetString("setting_bttnLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update User.
        /// </summary>
        public static string setting_bttnUserName {
            get {
                return ResourceManager.GetString("setting_bttnUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Language.
        /// </summary>
        public static string setting_lblLanguage {
            get {
                return ResourceManager.GetString("setting_lblLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current User(Author).
        /// </summary>
        public static string setting_lblUserName {
            get {
                return ResourceManager.GetString("setting_lblUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to John Doe.
        /// </summary>
        public static string setting_ntrUserName {
            get {
                return ResourceManager.GetString("setting_ntrUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string viewRecipes_bttnDelete {
            get {
                return ResourceManager.GetString("viewRecipes_bttnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string viewRecipes_bttnEdit {
            get {
                return ResourceManager.GetString("viewRecipes_bttnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Information.
        /// </summary>
        public static string viewRecipes_lblGeneralInformation {
            get {
                return ResourceManager.GetString("viewRecipes_lblGeneralInformation", resourceCulture);
            }
        }
    }
}
