//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CookBookApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CookBookApp.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string addRecipes_bttnBack {
            get {
                return ResourceManager.GetString("addRecipes_bttnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string addRecipes_bttnForward {
            get {
                return ResourceManager.GetString("addRecipes_bttnForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allergens.
        /// </summary>
        public static string addRecipes_lblAllergens {
            get {
                return ResourceManager.GetString("addRecipes_lblAllergens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string addRecipes_lblAuthor {
            get {
                return ResourceManager.GetString("addRecipes_lblAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string addRecipes_lblCategories {
            get {
                return ResourceManager.GetString("addRecipes_lblCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulty.
        /// </summary>
        public static string addRecipes_lblDifficulty {
            get {
                return ResourceManager.GetString("addRecipes_lblDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portions.
        /// </summary>
        public static string addRecipes_lblPortion {
            get {
                return ResourceManager.GetString("addRecipes_lblPortion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparation time.
        /// </summary>
        public static string addRecipes_lblPreparationTime {
            get {
                return ResourceManager.GetString("addRecipes_lblPreparationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string addRecipes_lblPrice {
            get {
                return ResourceManager.GetString("addRecipes_lblPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe Name.
        /// </summary>
        public static string addRecipes_lblRecipeName {
            get {
                return ResourceManager.GetString("addRecipes_lblRecipeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lactose, Peanuts, etc....
        /// </summary>
        public static string addRecipes_ntrAllergens {
            get {
                return ResourceManager.GetString("addRecipes_ntrAllergens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to John Doe.
        /// </summary>
        public static string addRecipes_ntrAuthor {
            get {
                return ResourceManager.GetString("addRecipes_ntrAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4....
        /// </summary>
        public static string addRecipes_ntrPortion {
            get {
                return ResourceManager.GetString("addRecipes_ntrPortion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 hours....
        /// </summary>
        public static string addRecipes_ntrPreparationTime {
            get {
                return ResourceManager.GetString("addRecipes_ntrPreparationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100....
        /// </summary>
        public static string addRecipes_ntrPrice {
            get {
                return ResourceManager.GetString("addRecipes_ntrPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lasagne.
        /// </summary>
        public static string addRecipes_ntrRecipeName {
            get {
                return ResourceManager.GetString("addRecipes_ntrRecipeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Recipe.
        /// </summary>
        public static string menu_bttnAddRecipes {
            get {
                return ResourceManager.GetString("menu_bttnAddRecipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipes.
        /// </summary>
        public static string menu_bttnRecipes {
            get {
                return ResourceManager.GetString("menu_bttnRecipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string menu_bttnSettings {
            get {
                return ResourceManager.GetString("menu_bttnSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main page.
        /// </summary>
        public static string menu_lblMenu {
            get {
                return ResourceManager.GetString("menu_lblMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string recipes_bttnBack {
            get {
                return ResourceManager.GetString("recipes_bttnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string recipes_bttnFilter {
            get {
                return ResourceManager.GetString("recipes_bttnFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.....
        /// </summary>
        public static string recipes_srchBrRecipes {
            get {
                return ResourceManager.GetString("recipes_srchBrRecipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string setting_bttnBack {
            get {
                return ResourceManager.GetString("setting_bttnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Language.
        /// </summary>
        public static string setting_bttnLanguage {
            get {
                return ResourceManager.GetString("setting_bttnLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update User.
        /// </summary>
        public static string setting_bttnUserName {
            get {
                return ResourceManager.GetString("setting_bttnUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Language.
        /// </summary>
        public static string setting_lblLanguage {
            get {
                return ResourceManager.GetString("setting_lblLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current User(Author).
        /// </summary>
        public static string setting_lblUserName {
            get {
                return ResourceManager.GetString("setting_lblUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to John Doe.
        /// </summary>
        public static string setting_ntrUserName {
            get {
                return ResourceManager.GetString("setting_ntrUserName", resourceCulture);
            }
        }
    }
}
